version: "3.8"

name: vs

networks:
  backend:
    driver: bridge

services:
  playground-cuda:
    image: lychee0/vs-playground:cuda
    container_name: playground-cuda
    restart: always
    ports:
      - "1145:8888"
      - "1022:22"
    volumes:
      - ./video:/video
    environment:
      - JUPYTER_TOKEN=114514
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
              capabilities: [gpu]
    networks:
      - backend
