version: "3.8"

name: vs

networks:
  backend:
    driver: bridge

services:
  playground:
    image: lychee0/vs-playground:dev
    container_name: playground
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./video:/video
    environment:
      - JUPYTER_TOKEN=114514
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
              capabilities: [gpu]
    networks:
      - backend
