version: 2.1

jobs:
  build-cuda:
    docker:
      - image: cimg/go:1.17
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo $DOCKERHUB_PASSWORD | docker login -u lychee0 --password-stdin
          make release

  build-rocm:
    docker:
      - image: cimg/go:1.17
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo $DOCKERHUB_PASSWORD | docker login -u lychee0 --password-stdin
          make release-rocm

workflows:
  version: 2
  build_all:
    jobs:
      - build-cuda
      - build-rocm
