version: 2.1

jobs:
  build-cuda:
    docker:
      - image: cimg/go:1.17
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo $DOCKERHUB_PASSWORD | docker login -u lychee0 --password-stdin
          make release

  build-rocm:
    docker:
      - image: cimg/go:1.17
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo $DOCKERHUB_PASSWORD | docker login -u lychee0 --password-stdin
          make release-rocm

  build-cuda-dev:
    docker:
      - image: cimg/go:1.17
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo $DOCKERHUB_PASSWORD | docker login -u lychee0 --password-stdin
          make release-dev

  build-rocm-dev:
    docker:
      - image: cimg/go:1.17
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo $DOCKERHUB_PASSWORD | docker login -u lychee0 --password-stdin
          make release-rocm-dev

workflows:
  version: 2
  build_all:
    jobs:
      - build-cuda:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-rocm:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-cuda-dev
      - build-rocm-dev
