name: Docker Build CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - LICENSE
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lychee0
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build vs-ffmpeg-base
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          file: vs-ffmpeg-base.dockerfile
          tags: lychee0/vs-ffmpeg-base:dev

      - name: Build vs-pytorch
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          file: vs-pytorch.dockerfile
          tags: lychee0/vs-pytorch:dev

      - name: Build vs-playground
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          file: vs-playground.dockerfile
          tags: lychee0/vs-playground:dev
