name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  Release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Release
        uses: softprops/action-gh-release@v2
