name: Release

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker # use local image for chain builds

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lychee0
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta vs-pytorch
        id: meta1
        uses: docker/metadata-action@v5
        with:
          images: |
            lychee0/vs-pytorch
          tags: |
            latest
            cuda
            cuda-${{ github.ref_name }}

      - name: Build vs-pytorch
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          file: vs-pytorch.dockerfile
          tags: ${{ steps.meta1.outputs.tags }}

      - name: Docker meta vs-playground
        id: meta2
        uses: docker/metadata-action@v5
        with:
          images: |
            lychee0/vs-playground
          tags: |
            latest
            cuda
            cuda-${{ github.ref_name }}

      - name: Build vs-playground
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          file: vs-playground.dockerfile
          tags: ${{ steps.meta2.outputs.tags }}
          build-args: |
            BASE_CONTAINER_TAG=latest

  github:
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Release
        uses: softprops/action-gh-release@v2
