name: Release

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker # use local image for chain builds

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lychee0
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build vs-pytorch
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          file: vs-pytorch.dockerfile
          tags: |
            lychee0/vs-pytorch:latest
            lychee0/vs-pytorch:cuda
            lychee0/vs-pytorch:cuda-${{ github.ref_name }}

      - name: Build vs-playground
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          file: vs-playground.dockerfile
          tags: |
            lychee0/vs-playground:latest
            lychee0/vs-playground:cuda
            lychee0/vs-playground:cuda-${{ github.ref_name }}
          build-args: |
            BASE_CONTAINER_TAG=cuda-${{ github.ref_name }}

  github:
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Release
        uses: softprops/action-gh-release@v2
